GarageVersion3/Models/ParkingLot.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GarageVersion3.Models
{
    public class ParkingLot
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("Vehicle")]
        public int VehicleId { get; set; }
        public Vehicle? Vehicle { get; set; }
        [Range(1,25, ErrorMessage = "We only have parking spots ranging from 1 - 25.")]
        public int ParkingSpot { get; set; }
        public bool AvailableParkingSpot { get; set; }
        public DateTime Checkin { get; set; }
    }
}

GarageVersion3/Models/ViewModels/ParkingLotViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace GarageVersion3.Models.ViewModels
{
    public class ParkingLotViewModel
    {
        public int Id { get; set; }
        
        public int UserId { get; set; }

        public int VehicleId { get; set; }
        
        public string? User { get; set; }

        [Display(Name = "Registration Number")]
        public string? RegistrationNumber { get; set; }

     
        public DateTime Checkin { get; set; }

        [Display(Name = "Parking Spot")]
        public int ParkingSpot { get; set; }

        public VehicleViewModel? VehicleViewModel { get; set; }

    }
}

GarageVersion3/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageVersion3.Data;
using GarageVersion3.Models;
using GarageVersion3.Models.ViewModels;

namespace GarageVersion3.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly GarageVersion3Context _context;

        public VehiclesController(GarageVersion3Context context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = await _context.Vehicle
                .Include(v => v.User)
                .Include(v => v.VehicleType)
                .Select(v => new VehicleViewModel
                {
                    Id = v.Id,
                    RegistrationNumber = v.RegistrationNumber,
                    User = $"{v.User.FirstName} {v.User.LastName} ({v.User.PersonalIdentifyNumber})",
                    VehicleType = v.VehicleType.Type,
                }).ToListAsync();

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _context.Vehicle
                .Where(v => v.Id == id)
                .Include(v => v.User)
                .Include(v => v.VehicleType)
                .Select(v => new VehicleViewModel
                {
                    Id = v.Id,
                    User = $"{v.User.FirstName} {v.User.LastName} ({v.User.PersonalIdentifyNumber})",
                    VehicleType = v.VehicleType.Type,
                    RegistrationNumber = v.RegistrationNumber,
                    Brand = v.Brand,
                    Color = v.Color,
                    VehicleModel = v.VehicleModel,
                    NrOfWheels = v.NrOfWheels
                }).FirstOrDefaultAsync();

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            DropdownDataLists();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                bool existingVehicle = _context.Vehicle.Any(v => v.RegistrationNumber.ToUpper().Trim().Replace(" ", "").Equals(viewModel.RegistrationNumber.Trim().ToUpper().Replace(" ", "")));
                int nrOfCharacters = viewModel.RegistrationNumber.ToUpper().Trim().Replace(" ", "").Count();

                  
                if (existingVehicle || nrOfCharacters < 6)
                {
                    ModelState.AddModelError("RegistrationNumber", existingVehicle ? "A vehicle with this registration number already exists":
                                                                                     "Registration number must be between 6 and 10");
                    DropdownDataLists();
                    return View();
                }

                var vehicle = new Vehicle
                {
                    VehicleTypeId = viewModel.VehicleTypeId,
                    UserId = viewModel.UserId,
                    RegistrationNumber = viewModel.RegistrationNumber.ToUpper().Trim().Replace(" ",""),
                    Brand = viewModel.Brand.Trim(),
                    Color = viewModel.Color.Trim(),
                    VehicleModel = viewModel.VehicleModel.Trim(),
                    NrOfWheels = viewModel.NrOfWheels,
                };

                _context.Add(vehicle);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            DropdownDataLists();
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var viewModel = new VehicleViewModel
            {
                Id = vehicle.Id,
                VehicleTypeId = vehicle.VehicleTypeId,
                UserId = vehicle.UserId,
                RegistrationNumber = vehicle.RegistrationNumber,
                Brand = vehicle.Brand,
                Color = vehicle.Color,
                VehicleModel = vehicle.VehicleModel,
                NrOfWheels = vehicle.NrOfWheels
            };


            DropdownDataLists();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VehicleViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var vehicle = await _context.Vehicle.FindAsync(id);

                    if (vehicle == null)
                    {
                        return NotFound();
                    }

                    var existingVehicleWithSameRegNumber = await _context.Vehicle
                        .Where(v => v.Id != id && v.RegistrationNumber.ToUpper().Trim().Replace(" ", "").Equals(viewModel.RegistrationNumber.ToUpper().Trim().Replace(" ", "")))
                        .FirstOrDefaultAsync();

                    int nrOfCharacters = viewModel.RegistrationNumber.ToUpper().Trim().Replace(" ", "").Count();

                    if (existingVehicleWithSameRegNumber != null || nrOfCharacters < 6)
                    {
                        ModelState.AddModelError("RegistrationNumber", (existingVehicleWithSameRegNumber != null) ? "A vehicle with this registration number already exists" : "Registration number must be between 6 and 10");
                        DropdownDataLists();
                        return View();
                    }

                    vehicle.VehicleTypeId = viewModel.VehicleTypeId;
                    vehicle.UserId = viewModel.UserId;
                    vehicle.RegistrationNumber = viewModel.RegistrationNumber.ToUpper().Trim().Replace(" ", "");
                    vehicle.Brand = viewModel.Brand.Trim();
                    vehicle.Color = viewModel.Color.Trim();
                    vehicle.VehicleModel = viewModel.VehicleModel.Trim();
                    vehicle.NrOfWheels = viewModel.NrOfWheels;

                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            DropdownDataLists();
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FirstOrDefaultAsync(v => v.Id == id);
            var vehicleType = await _context.VehicleType.FirstOrDefaultAsync(vt => vt.Id == vehicle.VehicleTypeId);
            var user = await _context.User.FirstOrDefaultAsync(u => u.Id == vehicle.UserId);


            if (vehicle == null || vehicleType == null || user == null)
            {
                return NotFound();
            }

            var viewModel = new VehicleViewModel
            {
                Id = vehicle.Id,
                VehicleTypeId = vehicleType.Id,
                VehicleType = vehicleType.Type,
                UserId = vehicle.UserId,
                User = $"{user.FirstName} {user.LastName} ({user.PersonalIdentifyNumber})",
                RegistrationNumber = vehicle.RegistrationNumber,
                Brand = vehicle.Brand,
                Color = vehicle.Color,
                VehicleModel = vehicle.VehicleModel,
                NrOfWheels = vehicle.NrOfWheels
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var vehicle = await _context.Vehicle.FindAsync(id);

                if (vehicle == null)
                {
                    return NotFound();
                }

                _context.Vehicle.Remove(vehicle);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error occured while trying to remove a vehicle");
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Sort(string sortOrder)
        {
            var vehicles = await _context.Vehicle
                .Include(v => v.VehicleType)
                .Include(v => v.User)
                .ToListAsync();

            if (vehicles.Count() == 0)
            {
                TempData["SortOnEmptyList"] = "The list is empty";
                return RedirectToAction(nameof(Index));
            }

            switch (sortOrder)
            {
                case "VehicleType":

GarageVersion3/Views/ParkingLot/Create.cshtml
@model IEnumerable<VehicleViewModel>

@{
    ViewData["Title"] = "Check In";
}


@if (TempData.ContainsKey("SearchMessage"))
{
    var message = TempData["SearchMessage"] as string;
    var status = TempData["SearchStatus"] as string;

    <div class="@status" role="alert">
        @message
    </div>
}

<div class="container-fluid">
    <h1 class="display-4 text-center mt-4">Check In Vehicle</h1>

    <div class="row justify-content-center">
        <div class="text-center mt-4 mb-3">
            <a asp-action="ShowAll" asp-route-status="false" class="btn btn-primary-blue">Show All</a>
            <a asp-action="Index" class="btn btn-secondary-blue ms-2">Back to List</a>
        </div>

        <form asp-action="FilterCreate" method="get" class="form-inline m-3 d-flex flex-column align-items-center">
            <p>Choose 1-3 attributes for searching a user</p>
            <div class="d-flex flex-row input-group-sm align-items-center">
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="firstName" placeholder="Search by first name">
                </div>
                
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="lastName" placeholder="Search by last name">
                </div>

                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="vehicleType" placeholder="Search by vehicle type">
                </div>
                <div>
                    <button type="submit" class="btn btn-mid-blue ms-2">Search</button>
                </div>
            </div>
        </form>
    </div>

    <form asp-action="Create" method="post">        

        <table class="table mt-3">
            <thead>
                <tr>
                    <th class="pb-3 h5 text-left font-weight-bold">
                        Owner
                    </th>
                    <th class="pb-3 h5 text-left font-weight-bold">
                        Vehicle Type
                    </th>

                     <th class="pb-3 h5 text-left font-weight-bold">
                        Registration Number
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.VehicleType)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.RegistrationNumber)
                        </td>

                        <td align="right">
                            <button type="submit" name="vehicleId" value="@item.Id" class="btn btn-primary-blue">Check In</button>
                        </td> 
                    </tr>
                }
            </tbody>
        </table>

    </form>

</div>

GarageVersion3/Views/ParkingLot/Delete.cshtml
@model ParkingLotViewModel

@{
    ViewData["Title"] = "Check Out";
}

<div class="container">
    <h1 class="display-4 mt-4">Check Out Vehicle</h1>
    <div class="row">
        <h3 class="mt-2 mb-4">Are you sure you want to check out this vehicle?</h3>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.User)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.User)
            </dd>

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.RegistrationNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.ParkingSpot)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.ParkingSpot)
            </dd>
   
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Checkin)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Checkin)
            </dd>
        </dl>
        <div class="pt-2">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Check Out" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-dark-blue ms-2">Back to List</a>
            </form>
        </div>
    </div>
</div>

GarageVersion3/Views/ParkingLot/Details.cshtml
@model ParkingLotViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1 class="display-4 mt-4">Parking Spot Details</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.User)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.ParkingSpot)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.ParkingSpot)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Checkin)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Checkin)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.RegistrationNumber)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.RegistrationNumber)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.VehicleType)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.VehicleType)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.Brand)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.Brand)
        </dd>
            <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.VehicleModel)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.VehicleModel)
        </dd>
            <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.Color)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.Color)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.VehicleViewModel.NrOfWheels)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.VehicleViewModel.NrOfWheels)
        </dd>
    </dl>
    <div class="pt-2">
        <a asp-controller="Vehicles" asp-action="Edit" asp-route-id="@Model.VehicleId" class="btn btn-primary-blue">Edit</a>
        <a asp-action="Index" class="btn btn-dark-blue ms-2">Back to list</a>
    </div>
</div>

GarageVersion3/Views/ParkingLot/Index.cshtml
@model IEnumerable<ParkingLotViewModel>

@{
    ViewData["Title"] = "Parking Lot";
}



@if (TempData.ContainsKey("SearchMessage"))
{
    var message = TempData["SearchMessage"] as string;
    var status = TempData["SearchStatus"] as string;

    <div class="@status" role="alert">
        @message
    </div>
}

<div class="container-fluid">
    <h1 class="display-4 text-center mt-4">Parking Lot</h1>

    <div class="row justify-content-center">

        <div class="mt-3 mb-3">
            @if(ViewBag.Vehicles == 0)
            {
                <h2 class="h5 text-center">Parking spots full</h2>
            }

            else{
                <h2 class="h5 text-center">Parking spots left: @ViewBag.Vehicles</h2>
            }
        </div>

        <div class="mt-3 mb-3 text-center">
            @if (ViewBag.Vehicles == 0)
            {
                <button class="btn btn-primary-blue" disabled="true">Park Vehicle</button>
            }
            else
            {
                <a asp-action="Create" class="btn btn-primary-blue">Check In</a>
            }

            <a asp-action="ShowAll" asp-route-status="true" class="btn btn-secondary-blue ms-2">Show All Parked Vehicles</a>
        </div>

        <form asp-action="FilterIndex" method="get" class="form-inline m-3 d-flex flex-column align-items-center">
            <p>Choose 1-3 attributes for searching a user</p>
            <div class="d-flex flex-searchbar input-group-sm align-items-center">
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="firstName" placeholder="Search by first name">
                </div>
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="lastName" placeholder="Search by last name">
                </div>
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="vehicleType" placeholder="Search by vehicle type">
                </div>
                <div>
                    <button type="submit" class="btn btn-mid-blue ms-2">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div>
        <table class="table mt-3">
            <thead>
                <tr>
                    <th class="pb-3 table-txt text-left font-weight-bold">
                        Owner
                    </th>

                    <th class="pb-3 table-txt text-left font-weight-bold">
                        Vehicle Type
                    </th>

                    <th class="pb-3 table-txt text-left font-weight-bold">
                        Registration Number
                    </th>

                    <th class="pb-3 table-txt text-left font-weight-bold">
                        Check In
                    </th>

                    <th class="pb-3 table-txt text-left font-weight-bold">
                        Parking Spot
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="index-page">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VehicleViewModel.VehicleType)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.RegistrationNumber)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Checkin)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.ParkingSpot)
                        </td>

                        <td align="right">

                            <a asp-controller="Vehicles" asp-action="Edit" asp-route-id="@item.VehicleId" class="btn btn-primary-blue">Edit</a> 
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary-blue ms-2">Details</a> 
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger ms-2">Check Out</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>