GarageVersion3/Models/Receipt.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GarageVersion3.Models
{
    public class Receipt
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("User")]
        public int UserId { get; set; }
        public User? User { get; set; }

        [Range(1,int.MaxValue,ErrorMessage = "No negative value")]
        public int ParkingNumber { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }

        [Range(0.0, double.MaxValue, ErrorMessage = "Price can't be less than 0")]
        public double Price { get; set; }
    }
}

GarageVersion3/Models/ViewModels/ReceiptViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GarageVersion3.Models.ViewModels
{
    public class ReceiptViewModel
    {
        public int Id { get; set; }
        public User User { get; set; }
        
        [Display(Name = "Vehicle Type")]
        public VehicleType VehicleType { get; set; }

        [Display(Name = "Registration Number")]
        public string RegistrationNumber { get; set; }

        [Display(Name = "Parking Spot")]
        public int ParkingNumber { get; set; }

        [Display(Name = "Check in Date")]
        public DateTime CheckIn { get; set; }

        [Display(Name = "Check out Date")]
        public DateTime CheckOutDate { get; set; }

        [Display(Name = "Total Hours of Parking")]
        public int TotalParkingHours { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:N} SEK")]
        public double Price { get; set; }

        public void CalculateTotalParkingHours()
        {
            TimeSpan parkingDuration = CheckOutDate - CheckIn;
            TotalParkingHours = (int)parkingDuration.TotalHours;
        }

        public void CalculatePrice()
        {
            const double HourlyRate = 50;
            Price = TotalParkingHours * HourlyRate;
        }
    }
}

GarageVersion3/Controllers/ReceiptsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GarageVersion3.Data;
using GarageVersion3.Models.ViewModels;

namespace GarageVersion3.Controllers
{
    public class ReceiptsController : Controller
    {
        private readonly GarageVersion3Context _context;

        public ReceiptsController(GarageVersion3Context context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            TempData["Users"] = await _context.User.ToListAsync();

            var viewModel = await _context.Receipt
                    .Include(r => r.User)
                    .Select(r => new ReceiptViewModel
                    {
                        Id = r.Id,
                        User = r.User,
                        CheckIn = r.CheckIn,
                        CheckOutDate = r.CheckOut,
                        Price = r.Price,
                        ParkingNumber = r.ParkingNumber
                    }).ToListAsync();

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetUserReceiptsByPersonalNumber(string selectedUserPersonalNr)
        {            
           TempData["Users"] = await _context.User.ToListAsync();

            if (string.IsNullOrEmpty(selectedUserPersonalNr))
            {
                TempData["SearchMessage"] = "You did not select a person number";
                TempData["SearchStatus"] = "alert alert-danger";
                return View("Index", new List<ReceiptViewModel>());
            }

            var user = _context.User.FirstOrDefault(u => u.PersonalIdentifyNumber == selectedUserPersonalNr);
            
            if (user == null)
            {
                return NotFound();
            }

            var userReceipts = await _context.Receipt
                .Where(u => u.UserId == user.Id)
                .Select(u => new ReceiptViewModel
                {
                    Id = u.Id,
                    User = u.User,
                    CheckIn = u.CheckIn,
                    CheckOutDate = u.CheckOut,
                    Price = u.Price,
                    ParkingNumber = u.ParkingNumber
                }).ToListAsync();

            TempData["SearchMessage"] = (userReceipts.Count() == 0) ? "User does not have any receipts" : "User receipts successfully showing up";
            TempData["SearchStatus"] = (userReceipts.Count() == 0) ? "alert alert-warning" : "alert alert-success";

            return View("Index",userReceipts);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _context.Receipt
                .Include(r => r.User)
                .Select(r => new ReceiptViewModel
                {
                    Id = r.Id,
                    User = r.User,
                    CheckIn = r.CheckIn,
                    CheckOutDate = r.CheckOut,
                    Price = r.Price,
                    ParkingNumber = r.ParkingNumber
                })
                .FirstOrDefaultAsync(r => r.Id == id);

            if(viewModel == null)
            {
                return NotFound();
            }
               
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Filter(string firstName, string lastName)
        {
            var query = _context.Receipt.AsQueryable();
            TempData["Users"] = await _context.User.ToListAsync();

            if (string.IsNullOrEmpty(firstName) && string.IsNullOrEmpty(lastName))
            {
                TempData["SearchMessage"] = "Please provide input for at least one search criteria";
                TempData["SearchStatus"] = "alert alert-warning";
                return View("Index", new List<ReceiptViewModel>());
            }

            if (!string.IsNullOrEmpty(firstName))
            {
                query = query.Where(u => u.User.FirstName.Replace(" ", "").Replace(" ", "").Trim().ToUpper().Equals(firstName.Replace(" ", "").ToUpper().Trim()));
            }

            if (!string.IsNullOrEmpty(lastName))
            {
                query = query.Where(u => u.User.LastName.Replace(" ", "").Trim().ToUpper().Equals(lastName.Replace(" ", "").ToUpper().Trim()));
            }

            var searchResults = await query
                .Include(r => r.User)
                .Select(r => new ReceiptViewModel
                {
                    Id = r.Id,
                    User = r.User,
                    CheckIn = r.CheckIn,
                    CheckOutDate = r.CheckOut,
                    Price = r.Price,
                    ParkingNumber = r.ParkingNumber
                }).ToListAsync();

            TempData["SearchMessage"] = (searchResults.Count() == 0) ? "No receipts where found on the search user" : "Search was successful";
            TempData["SearchStatus"] = (searchResults.Count() == 0) ? "alert alert-warning" : "alert alert-success";

            return View("Index", searchResults);
        }

        [HttpGet]
        public IActionResult ShowAll()
        {
            TempData["SearchMessage"] = (_context.Receipt.Count() == 0) ? "There are no receipts" : "Showing all receipts was successful";
            TempData["SearchStatus"] = (_context.Receipt.Count() == 0) ? "alert alert-warning" : "alert alert-success";

            return RedirectToAction(nameof(Index));
        }

        private bool ReceiptExists(int id)
        {
            return _context.Receipt.Any(e => e.Id == id);
        }
    }
}

GarageVersion3/Views/Receipts/Details.cshtml
@model ReceiptViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1 class="display-4 mt-4">Receipt Details</h1>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName) 
            @Html.DisplayFor(model => model.User.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParkingNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParkingNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOutDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckOutDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    <div class="pt-2">
        <a asp-action="Index" class="btn btn-dark-blue">Back to list</a>
    </div>
</div>

GarageVersion3/Views/Receipts/Index.cshtml
@model IEnumerable<ReceiptViewModel>

@{
    ViewData["Title"] = "Index";
}


@if (TempData.ContainsKey("SearchMessage"))
{
    var message = TempData["SearchMessage"] as string;
    var status = TempData["SearchStatus"] as string;

    <div class="@status" role="alert">
        @message
    </div>
}

<div class="container-fluid">
    <h1 class="display-4 text-center mt-4">Receipts</h1>

    <div class="row justify-content-center">
        <div class="text-center mt-4 mb-3">
            <a asp-action="ShowAll" class="btn btn-secondary-blue">Show All Receipts</a>
        </div>

        <form asp-action="Filter" method="get" class="form-inline m-3 d-flex flex-column align-items-center">
            <p>Choose 1-2 attributes to search for users receipts</p>
            <div class="d-flex flex-row input-group-sm align-items-center">
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="firstName" placeholder="Search by first name">
                </div>
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="lastName" placeholder="Search by last name">
                </div>
                <div>
                    <button type="submit" class="btn btn-mid-blue ms-2">Search</button>
                </div>
            </div>
        </form>


        @{
            var userList = (List<User>)TempData["Users"];
        }

        <form asp-controller="Receipts" asp-action="GetUserReceiptsByPersonalNumber" method="get" class="form-inline m-3 d-flex flex-column align-items-let">
            <div class="d-flex flex-row input-group-sm align-items-center">
                <button type="submit" class="btn btn-mid-blue">Submit</button>

                <div class="form-group mr-2">
                    <select id="userDropdown" name="selectedUserPersonalNr" class="form-control ms-2">
                        <option value="">Select A Personal Number</option>
                        @foreach (var user in userList)
                        {
                            <option value="@user.PersonalIdentifyNumber">@user.PersonalIdentifyNumber</option>
                        }
                    </select>
                </div>
            </div>
        </form>
    </div>
    

    <table class="table mt-3">
        <thead>
            <tr>
                <th class="pb-3 table-txt text-left">
                    @Html.DisplayNameFor(model => model.User)
                </th>
                <th class="pb-3 table-txt text-left">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="index-page">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.FirstName)
                        @Html.DisplayFor(modelItem => item.User.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td align="right">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary-blue">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>